CholitoProject/complaint/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', ComplaintView, name='complaint-form'),
    url(r'^send', ComplaintSendView.as_view(), name='make-complaint'),
    url(r'^(?P<pk>\d+)/$', ComplaintRenderView.as_view(), name='see-complaint'),
    url(r'^act/(?P<pk>\d+)/$', ComplaintActState.as_view(), name='act-complaint'),
]

CholitoProject/complaint/models.py
from django.db import models

from municipality.models import Municipality


class AnimalType(models.Model):
    name = models.TextField(max_length=100)

    def __str__(self):
        return self.name


class Complaint(models.Model):
    COMPLAINT_OPTIONS = (
        (1, "Abandono en la calle"),
        (2, "Exposición a temperaturas extremas"),
        (3, "Falta de agua"),
        (4, "Falta de comida"),
        (5, "Violencia"),
        (6, "Venta ambulante"),
    )

    COMPLAINT_STATUS = (
        (1, "Reportada"),
        (2, "Consolidada"),
        (3, "Verificada"),
        (4, "Cerrada"),
        (5, "Desechada"),
    )
    COLOR_OPTIONS = (
        (1, "marron"),
        (2, "amarillo"),
        (3, "blanco"),
        (4, "gris"),
        (5, "manchado"),
    )

    GENDER_OPTIONS = (
        (1, "Macho"),
        (2, "Hembra"),
    )

    WOUND_OPTIONS = (
        (True, "Sí"),
        (False, "No"),
    )

    description = models.TextField(max_length=1000)
    case = models.SmallIntegerField(choices=COMPLAINT_OPTIONS)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    lng = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    directions = models.TextField(max_length=200, null=True)
    status = models.SmallIntegerField(choices=COMPLAINT_STATUS)
    animal_type = models.ForeignKey(AnimalType)
    gender = models.SmallIntegerField(choices=GENDER_OPTIONS)
    wounded = models.BooleanField(choices=WOUND_OPTIONS)
    color = models.SmallIntegerField(choices=COLOR_OPTIONS)
    municipality = models.ForeignKey(Municipality)

    def __str__(self):
        return "Complaint #" + str(self.pk)


class ComplaintImage(models.Model):
    image = models.ImageField(upload_to='complaints/')
    complaint = models.ForeignKey('Complaint', on_delete=models.CASCADE)

CholitoProject/complaint/forms.py
from django import forms
from municipality.models import Municipality
from .models import Complaint, AnimalType, ComplaintImage


class ComplaintForm(forms.Form):
    COMPLAINT_OPTIONS = (
        (1, "Abandono en la calle"),
        (2, "Exposición a temperaturas extremas"),
        (3, "Falta de agua"),
        (4, "Falta de comida"),
        (5, "Violencia"),
        (6, "Venta ambulante"),
    )

    COMPLAINT_STATUS = (
        (1, "Reportada"),
        (2, "Consolidada"),
        (3, "Verificada"),
        (4, "Cerrada"),
        (5, "Desechada"),
    )
    COLOR_OPTIONS = (
        (1, "Marron"),
        (2, "Amarillo"),
        (3, "Blanco"),
        (4, "Gris"),
        (5, "Manchado"),
    )

    GENDER_OPTIONS = (
        (1, "Macho"),
        (2, "Hembra"),
    )

    WOUND_OPTIONS = (
        (True, "Sí"),
        (False, "No"),
    )

    lat = forms.FloatField(widget=forms.HiddenInput(), required=True)
    lng = forms.FloatField(widget=forms.HiddenInput(), required=True)
    directions = forms.CharField(max_length=200, widget=forms.HiddenInput(), required=True)
    status = forms.ChoiceField(choices=COMPLAINT_STATUS, widget=forms.HiddenInput(), required=True, initial=1)
    animal_type = forms.ModelChoiceField(label="Tipo de animal", queryset=AnimalType.objects,
                                         widget=forms.Select(attrs={'class': 'form-control'}), required=True)
    caso = forms.ChoiceField(label="Caso de maltrato", choices=COMPLAINT_OPTIONS,
                             widget=forms.Select(attrs={'class': 'form-control'}), required=True)
    descripcion = forms.CharField(max_length=1000, widget=forms.TextInput(attrs={'class': 'form-control'}),
                                  required=True)
    sexo = forms.ChoiceField(choices=GENDER_OPTIONS, widget=forms.Select(attrs={'class': 'form-control'}),
                             required=True)
    color = forms.ChoiceField(choices=COLOR_OPTIONS, widget=forms.Select(attrs={'class': 'form-control'}),
                              required=True)
    herido = forms.ChoiceField(choices=WOUND_OPTIONS, widget=forms.Select(attrs={'class': 'form-control'}),
                               required=True)
    municipalidad = forms.ModelChoiceField(queryset=Municipality.objects,
                                           widget=forms.Select(attrs={'class': 'form-control'}), required=True)
    foto = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}), required=True)

    def is_valid(self):
        super(ComplaintForm, self).is_valid()

        return self.cleaned_data['status'] is not None

    def save(self):
        complaint = Complaint(description=self.cleaned_data['descripcion'], case=self.cleaned_data['caso'],
                              lat=self.cleaned_data['lat'], lng=self.cleaned_data['lng'],
                              directions=self.cleaned_data['directions'], status=self.cleaned_data['status'],
                              animal_type=self.cleaned_data['animal_type'], gender=self.cleaned_data['sexo'],
                              wounded=self.cleaned_data['herido'], color=self.cleaned_data['color'],
                              municipality=self.cleaned_data['municipalidad'])
        complaint.save()

        image = ComplaintImage(complaint=complaint, image=self.cleaned_data['foto'])
        image.save()


class ImageForm(forms.Form):
    complaint_image = forms.ImageField(
        widget=forms.FileInput(
            attrs={'id': 'image-input', 'class': "form-control", 'placeholder': "Agrega una imagen de tu denuncia"}))

CholitoProject/complaint/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.conf import settings

from CholitoProject.userManager import get_user_index
from complaint.forms import ComplaintForm, ImageForm
from complaint.models import Complaint, ComplaintImage, AnimalType


def ComplaintView(request):
    if request.POST:
        form = ComplaintForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()

        return redirect('/')

    else:
        form = ComplaintForm()
        user = get_user_index(request.user)

        return render(request, 'complaint.html', {'form': form, 'c_user': user, 'key': settings.GOOGLE_API_KEY})


class ComplaintSendView(View):
    def post(self, request, **kwargs):
        form = ComplaintForm(request.POST, prefix='complaint')
        image_form = ImageForm(request.POST, request.FILES, prefix='image')
        if form.is_valid():
            complaint = form.save(commit=False)
            complaint.status = 1
            complaint.save()
            if image_form.is_valid():
                ComplaintImage.objects.create(
                    complaint=complaint, image=image_form.cleaned_data.get('complaint_image'))

        return redirect('/')


class ComplaintRenderView(PermissionRequiredMixin, LoginRequiredMixin, View):
    template_name = 'view_complaint.html'
    permission_required = 'municipality.municipality_user_access'
    context = {}

    def get(self, request, pk, **kwargs):
        user = get_user_index(request.user)
        self.context['c_user'] = user
        complaint = get_object_or_404(Complaint, pk=pk)
        self.context['complaint'] = complaint

        images = ComplaintImage.objects.filter(complaint=complaint)
        self.context['images'] = images

        return render(request, self.template_name, context=self.context)


class ComplaintActState(PermissionRequiredMixin, LoginRequiredMixin, View):
    template_name = 'view_complaint.html'
    permission_required = 'municipality.municipality_user_access'
    context = {}

    def post(self, request, pk, **kwargs):
        complaint = get_object_or_404(Complaint, pk=pk)
        complaint.status = request.POST['status']
        complaint.save()

        self.context['complaint'] = complaint

        images = ComplaintImage.objects.filter(complaint=complaint)
        self.context['images'] = images
        # render(request, self.template_name, context=self.context)
        return redirect('see-complaint', pk=pk)

CholitoProject/complaint/templates/complaint.html
{% extends "User/user-standard.html" %}

{% block title %}Denuncia{% endblock %}

{% block content-header %}Subir Denuncia{% endblock %}

{% block content %}
    <div class="content container">
        <div class="row">
            <div class="col-md-8">

                <form method="POST" class="post-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table">
                        {% for field in form.hidden_fields %}
                            {{ field }}
                        {% endfor %}
                        {% for field in form.visible_fields %}
                            <tr>
                                <td>{{ field.label_tag }}</td>
                                <td>{{ field }}</td>
                                <td>{{ field.errors }}</td>
                            </tr>
                        {% endfor %}
                    </table>

                    <button type="submit" class="btn btn-lg btn-success" style="float: right; margin-right: 5%">
                        Agregar
                    </button>
                </form>
            </div>
        </div>
    </div>

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&key={{ key }}"></script>


    <script>
        google.maps.event.addDomListener(window, 'load', initialize);

        function initialize() {
            navigator.geolocation.getCurrentPosition(showPosition);
        }

        var showPosition = function (position) {
            var geocoder = new google.maps.Geocoder();
            var myLatlng1 = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);


            $('#id_lat').val(position.coords.latitude);
            $('#id_lng').val(position.coords.longitude);

            geocoder.geocode({'latLng': myLatlng1}, function (results, status) {
                alert("HOLI " + status)
                if (status == google.maps.GeocoderStatus.OK) {
                    $('#id_directions').val(results[0].formatted_address)
                }
            });
        };


    </script>

{% endblock %}

CholitoProject/complaint/templates/view_complaint.html
{% extends "Municipality/municipality-standard.html" %}
{% load static %}

{% block title %}Denuncia #{{ complaint.pk }}{% endblock %}

{% block content %}
    <h2 align="center">Denuncia #{{ complaint.pk }}</h2>
    <table class="table table-responsive">
        <tr>
            <th>Tipo de Denuncia:</th>
            <td>{{ complaint.get_case_display }}</td>
            <th>Tipo de Animal:</th>
            <td> {{ complaint.animal_type }}</td>
            <th>Color:</th>
            <td>{{ complaint.get_color_display }}</td>
        </tr>
        <tr>
            <th>Direccion:</th>
            <td>{{ complaint.directions }}</td>
            <th>Sexo:</th>
            <td>{{ complaint.get_gender_display }}</td>
            <th>¿Herido?:</th>
            <td>{{ complaint.get_wounded_display }}</td>
        </tr>
        <tr>
            <th>Comentario:</th>
            <td colspan="5">{{ complaint.description }}</td>
        </tr>
    </table>
    {% if images %}
        <!-- slider -->
        <div class="row">
            <div class="col-md-9" id="slider">
                <!-- Top part of the slider -->
                <div class="row">
                    <div class="col-md-3" id="carousel-bounding-box">
                        <div id="myCarousel" class="carousel slide">
                            <!-- Carousel items -->
                            <div class="carousel-inner">

                                {% for image in images %}

                                    <div class="item"
                                            {% if forloop.counter0 == 0 %}
                                         id="slide0"
                                            {% endif %}
                                         data-slide-number="{{ forloop.counter0 }}">
                                        <img class="img-rounded img-responsive" src="{{ image.image.url }}">
                                    </div>

                                {% endfor %}

                            </div><!--/carousel-inner-->
                        </div><!--/carousel-->
                        <ul class="carousel-controls-mini list-inline text-center">
                            <li><a href="#myCarousel" data-slide="prev">‹</a></li>
                            <li><a href="#myCarousel" data-slide="next">›</a></li>
                        </ul><!--/carousel-controls-->
                    </div><!--/col-->
                    <div class="col-md-4" id="carousel-text"></div>

                </div><!--/row-->
            </div><!--/col-->
        </div><!--/row slider-->


        <script>
            $(document).ready(function () {
                jQuery("#slide0").addClass("active");
            });
        </script>

    {% endif %}

    <div class="text-center">
        <h3>Estado: <font color="#428bca"> {{ complaint.get_status_display }}</font></h3>

        <form method="POST" enctype="multipart/form-data" action="{% url 'act-complaint' complaint.pk %}">
            {% csrf_token %}

            <input type="hidden" name="id-complaint" id="id-complaint" value="{{ complaint.pk }}"/>
            <select class="btn btn-default btn-lg" id="status" name="status">
                <option value="1">Reportada</option>
                <option value="2">Consolidada</option>
                <option value="3">Verificada</option>
                <option value="4">Cerrada</option>
                <option value="5">Desechada</option>
            </select>

            <button type="submit" class="btn btn-primary btn-lg">Actualizar Estado</button>
        </form>


    </div>



{% endblock %}